.catalog:
  name: "PS"
  version: v4.3.0.5_20160720
  description: "PS Module."
  questions:
    - variable: "ps_scale"
      label: "PS Scale"
      required: true
      type: "int"
      default: 3
ps:
  scale: $ps_scale
  health_check:
    port: 8080
    response_timeout: 2000
    healthy_threshold: 2
    strategy: recreate
    unhealthy_threshold: 3
    interval: 2000
    request_line: GET "/ps/version: v4.3.0.5_20160720
memcached:
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 11211
    unhealthy_threshold: 3
    initializing_timeout: 10000
    interval: 2000
    strategy: recreate
