version: '2'
services:
  wag:
    image: 10.50.131.32:8080/library/wag:2.6.0.1_20160122
    volumes:
    - /usr/nettv/logs/wag:/usr/nettv/logs
    - /usr/nettv/conf/wag:/usr/nettv/apps/wag/WEB-INF/conf:ro
    labels:
    - "app=wag"
#    external_links:
#    - loadbalance/lb:lb
