.catalog:
  name: "loadbalance"
  version: "v0.1.0"
  description: "Internal Load Balance"
  questions:
    - variable: "global_service"
      label: "Global Service"
      description: |
        Enable this option to run a load balance container on every host in the environment.
      required: true
      type: "boolean"
      default: true
    - variable: "real_port"
      label: "Real Host Port"
      description: "port to access Real Host."
      required: true
      default: "80"
      type: "int"
lb:
  health_check:
    port: 8080
    response_timeout: 2000
    healthy_threshold: 2
    strategy: recreate
    unhealthy_threshold: 3
    interval: 2000
    request_line: GET "/nginx_status" "HTTP/1.0"
