metadata-version = "2015-12-19"
log-level = "debug"
interval = 10
onetime = false

[[template]]
source = "/etc/rancher-gen/nginx.tmpl"
dest = "/usr/local/openresty/nginx/conf/nginx.conf"
check-cmd = "/usr/local/openresty/nginx/sbin/nginx -t -c {{staging}}"
notify-cmd = "/etc/init.d/openresty reload"
notify-output = true
