version: '2'
services:
  aaa:
    image: registry:5000/aaa:3.1.2.8_20160413
    volumes:
    - /opt/logs/app/aaa/b2c:/usr/nettv/logs
    - /usr/nettv/conf/b2c/aaa:/usr/nettv/conf/aaa:ro
    labels:
      traefik.domain: aaa
      traefik.port: '8080'
      traefik.enable: 'true'
    external_links:
    - loadbalance/lb:lb
