version: '2'
services:
  aaa:
    image: 10.50.131.32:8080/library/aaa:3.1.2.8_20160413
    volumes:
    - /usr/nettv/logs/aaa:/usr/nettv/logs
    - /usr/nettv/conf/aaa:/usr/nettv/conf/aaa:ro
    cpuset: '0'
#    external_links:
#    - loadbalance/lb:lb
