.catalog:
  name: "AAA"
  version: "v3.1.2.8"
  description: "AAA Module."
  questions:
    - variable: "aaa_scale"
      label: "AAA Scale"
      required: true
      type: "int"
      default: 3
aaa:
  scale: $aaa_scale
  health_check:
    port: 8080
    response_timeout: 2000
    healthy_threshold: 2
    strategy: recreate
    unhealthy_threshold: 3
    interval: 2000
    request_line: GET "/tv/version.jsp" "HTTP/1.0"
