.catalog:
  name: "WAG"
  version: "v2.6.0.1"
  description: "WAG Module."
  questions:
    - variable: "wag_scale"
      label: "WAG Scale"
      required: true
      type: "int"
      default: 3
wag:
  scale: $wag_scale
  health_check:
    port: 8080
    response_timeout: 2000
    healthy_threshold: 2
    strategy: recreate
    unhealthy_threshold: 3
    interval: 2000
    request_line: GET "/wag/version.jsp" "HTTP/1.0"
