.catalog:
  name: "MyApp"
  version: "v1.1.0"
  description: "Demo Project."
  questions:
    - variable: "global_service"
      label: "Global Service"
      description: |
        Enable this option to run a load balance container on every host in the environment.
      required: true
      type: "boolean"
      default: true
    - variable: "real_port"
      label: "Real Host Port"
      description: "port to access Real Host."
      required: true
      default: "80"
      type: "int"
    - variable: "lb_port"
      label: "LB Port"
      description: "port to access Load Balance."
      required: true
      default: "80"
      type: "int"
    - variable: "backend_port"
      label: "Backend Port"
      description: |
        Port to use to connect to the configuration backend.
      required: true
      type: "int"
      default: "8080"
    - variable: "aaa_scale"
      label: "AAA Scale"
      required: true
      type: "int"
      default: 3
    - variable: "epg_scale"
      label: "EPG Scale"
      required: true
      type: "int"
      default: 3
    - variable: "wag_scale"
      label: "WAG Scale"
      required: true
      type: "int"
      default: 3
lb:
  lb_config:
    config: |-
      global
        log 127.0.0.1:8514 local0
        log 127.0.0.1:8514 local1 notice

      defaults
        log global
        option tcplog
    port_rules:
    - source_port: $lb_port
      target_port: $backend_port
      service: aaa
      protocol: http
      path: /tv
    - source_port: $lb_port
      target_port: $backend_port
      service: wag
      protocol: http
      path: /wag
    - source_port: $lb_port
      target_port: $backend_port
      service: epg
      protocol: http
      path: /epg
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 42
    unhealthy_threshold: 3
    interval: 2000
aaa:
  scale: $aaa_scale
wag:
  scale: $wag_scale
epg:
  scale: $epg_scale
