version: '2'
services:
  search:
    image: 10.50.131.32:8080/library/search:4.0.1_20161229.01
    volumes:
    - /usr/nettv/logs/search:/usr/nettv/logs
    - /usr/nettv/conf/search:/usr/nettv/apps/search/WEB-INF/conf:ro
    - /usr/nettv/lucene:/usr/nettv/lucene:ro
#    external_links:
#    - loadbalance/lb:lb
