.catalog:
  name: "SEARCH"
  version: "v4.0.1"
  description: "SEARCH Module."
  questions:
    - variable: "search_scale"
      label: "SEARCH Scale"
      required: true
      type: "int"
      default: 3
search:
  scale: $search_scale
  health_check:
    port: 8080
    response_timeout: 2000
    healthy_threshold: 2
    strategy: recreate
    unhealthy_threshold: 3
    interval: 2000
    request_line: GET "/search/version.jsp" "HTTP/1.0"
