version: '2'
services:
  myapplb:
    image: rancher/lb-service-haproxy:v0.4.6
    ports:
      - "80:80"
  aaa:
    image: registry:5000/aaa:2.16.3

  epg:
    image: registry:5000/epg:3.8.1

  wag:
    image: registry:5000/wag:2.5.2
