version: '2'
services:
  epg:
    image: 10.50.131.32:8080/library/epg:3.8.1_20160831.01
    volumes:
      - /usr/nettv/logs/epg:/usr/nettv/logs
      - /usr/nettv/conf/epg:/usr/nettv/apps/epg/WEB-INF/conf
#    external_links:
#    - loadbalance/lb:lb
