version: '2'
services:
  export:
    image: 10.50.131.32:8080/library/export:4.0.0_20161123.02
    volumes:
      - /usr/nettv/logs/export:/usr/nettv/logs
      - /usr/nettv/conf/export:/usr/nettv/apps/export/WEB-INF/conf:ro
      - /usr/nettv/lucene:/usr/nettv/lucene
    external_links:
    - loadbalance/lb:lb
